FROM alpine:3.20 AS build
RUN apk add --no-cache \
    build-base \
    cmake \
    pkgconfig \
    zeromq-dev \
    cppzmq
WORKDIR /app
COPY . .
RUN cmake -S . -B build && cmake --build build -j

FROM alpine:3.20
RUN apk add --no-cache libzmq
WORKDIR /app
COPY --from=build /app/build/load_manager /app/load_manager
CMD ["/app/load_manager"]
