apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
    nodePort: 30090
  - name: redis-exporter
    port: 9121
    targetPort: 9121
    nodePort: 30121
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 30379
